### ISSUE TITLE
Any plans to update the add-on?

### ISSUE THREAD

**Issue by gShahar** [shivamgoyal15/Add-Hotkeys-to-Coursera#2]
Add-on was removed from Firefox's library. Installing it manually returned an error, stating it maybe corrupt.

**Comment by shivamgly** [comment]
Hi gShahar, I am not working on the addon anymore. I made this when Coursera didn't use to support the keyboard, and to control the play speed more precisely. But now Coursera has added keyboard support, and for controlling the speed more precisely we can modify the local storage variables. 
Also, feel free to take the source code if you want to use it.

**Comment by shivamgly** [comment]
![image](https://user-images.githubusercontent.com/38981018/85973384-3161bd00-b9f0-11ea-915c-5dcb1a7ce0f6.png)

**Comment by gShahar** [comment]
Thanks for the update
